---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azurevote1
  namespace: azurevotens
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:1.21.*
spec:
  releaseName: azurevote2
  chart:
    git: git://github.com/nizlati/shiny-computing-machine
    ref: master
    path: azure-vote
  values:
    title: "Azure Vote App - Cats or Dogs?"
